name: Run Deploy Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch

jobs:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v1
- name: script
run: ./script.sh
shell: bash
