name: Run Deploy Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs: 
      name:
        description: "Who to greet"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Adding permission
        run: git update-index --chmod=+x ./.github/scripts/backend_decrypt.sh

      - uses: actions/checkout@v1
      - name: Script
        run: ./.github/scripts/deploy.sh
        shell: bash
